'use client';

// import type { Metadata } from "next";
import { usePathname } from "next/navigation"
import { Geist, Geist_Mono } from "next/font/google";
import { SectionProvider } from "./context/SectionContext";
import LandingNavbar from "./components/LandingNavbar";
import DefaultNavbar from "./components/DefaultNavbar";
import Footer from "./components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SectionProvider>
          {pathname === '/' ? <LandingNavbar /> : <DefaultNavbar />}
          {children}
          <Footer />
        </SectionProvider>
      </body>
    </html>
  );
}
